In [151]:
import numpy as np

In [152]:
# Generate a random 2D array of 3x3
# a = np.random.randint(0, 10, (4, 4))
a = np.array([
    [1, 2, 0, -1],
    [0, 2, 0, 1],
    [0, 6, 0, 1],
    [5, 2, 3, 0]
])
print(a)    

[[ 1  2  0 -1]
 [ 0  2  0  1]
 [ 0  6  0  1]
 [ 5  2  3  0]]


In [153]:
# take the DFT of the array
b = np.fft.fft2(a)
print(b)

[[ 22. +0.j   3.-11.j  -4. +0.j   3.+11.j]
 [ -5. +7.j   2. +4.j   7. +9.j   0. +0.j]
 [ -4. +0.j  -1. -5.j -10. +0.j  -1. +5.j]
 [ -5. -7.j   0. +0.j   7. -9.j   2. -4.j]]


In [154]:
c = np.array([
    [1, 1, 1, 1],
    [1, -1j, -1, 1j],
    [1, -1, 1, -1],
    [1, 1j, -1, -1j]
])
d = c @ a @ c
print(d)

[[ 22. +0.j   3.-11.j  -4. +0.j   3.+11.j]
 [ -5. +7.j   2. +4.j   7. +9.j   0. +0.j]
 [ -4. +0.j  -1. -5.j -10. +0.j  -1. +5.j]
 [ -5. -7.j   0. +0.j   7. -9.j   2. -4.j]]


In [155]:
# Generate DCT matrix given size
def DCT(size):
    matrix = np.zeros((size, size))
    for k in range(size):
        for n in range(size):
            a = np.sqrt(1/size) if k == 0 else np.sqrt(2/size)
            matrix[k, n] = (a * np.cos((np.pi*k/(2*size)) * (2*n + 1))) * (1/np.sqrt(size))*size

    return np.round(matrix, 15)
print(DCT(4)) 

[[ 1.          1.          1.          1.        ]
 [ 1.30656296  0.5411961  -0.5411961  -1.30656296]
 [ 1.         -1.         -1.          1.        ]
 [ 0.5411961  -1.30656296  1.30656296 -0.5411961 ]]


In [156]:
(1/np.sqrt(2/4) * np.cos((np.pi*0/(2*4)) * (2*0 + 1))) * (1/np.sqrt(4))*4

2.82842712474619

In [157]:
# take the dft of 
a = np.array([
    [1, 2, 1],
    [1, 2, 1],
    [1, 2, 1]
])
b = np.fft.fft2(a)
print(b)


[[12. +0.j         -1.5-2.59807621j -1.5+2.59807621j]
 [ 0. +0.j          0. +0.j          0. +0.j        ]
 [ 0. +0.j          0. +0.j          0. +0.j        ]]


In [158]:
np.fft.ifft2(np.fft.fft2((1/9)*np.ones((3,3))) * b)

array([[1.33333333+0.j, 1.33333333+0.j, 1.33333333+0.j],
       [1.33333333+0.j, 1.33333333+0.j, 1.33333333+0.j],
       [1.33333333+0.j, 1.33333333+0.j, 1.33333333+0.j]])

In [159]:
# np.fft.fft2((1/9)*np.ones((3,3))) * b
c = np.array([
    [1, 1, 1],
    [1, (-1/2) - 1j*(np.sqrt(3)/2), (-1/2) + 1j*(np.sqrt(3)/2)],
    [1, (-1/2) + 1j*(np.sqrt(3)/2), (-1/2) - 1j*(np.sqrt(3)/2)]
])
d = (np.fft.fft2((1/9)*np.ones((3,3))) * b) @ c
print(d)

[[12.+0.j 12.+0.j 12.+0.j]
 [ 0.+0.j -0.+0.j -0.+0.j]
 [ 0.+0.j -0.+0.j -0.+0.j]]


In [160]:
# np.fft.fft2((1/9)*np.ones((3,3))) * b
c = np.array([
    [1, 1, 1],
    [1, (-1/2), (-1/2)],
    [1, (-1/2), (-1/2)]
])
d = (np.fft.fft2((1/9)*np.ones((3,3))) * b) @ c
print(d)

[[12.+0.j 12.+0.j 12.+0.j]
 [ 0.+0.j -0.+0.j -0.+0.j]
 [ 0.+0.j -0.+0.j -0.+0.j]]


In [161]:
a = np.array([
    [2, 2],
    [0, 0]
])
b = np.fft.fft2(a)
print(b)

[[4.+0.j 0.+0.j]
 [4.+0.j 0.+0.j]]


In [162]:
a = np.array([
    [1, 2, 1],
    [2, 4, 2],
    [1, 2, 1]
])
b = np.fft.fft2(a)
print(b)


[[16. +0.00000000e+00j -2. -3.46410162e+00j -2. +3.46410162e+00j]
 [-2. -3.46410162e+00j -0.5+8.66025404e-01j  1. -1.11022302e-16j]
 [-2. +3.46410162e+00j  1. +1.11022302e-16j -0.5-8.66025404e-01j]]


In [163]:
DCT(4) @ DCT(4).T

array([[ 4.00000000e+00,  2.22044605e-16,  0.00000000e+00,
        -1.11022302e-15],
       [ 2.22044605e-16,  4.00000000e+00,  0.00000000e+00,
        -5.68615185e-16],
       [ 0.00000000e+00,  0.00000000e+00,  4.00000000e+00,
         9.99200722e-16],
       [-1.11022302e-15, -5.68615185e-16,  9.99200722e-16,
         4.00000000e+00]])

In [164]:
# Create DFT matricies
def DFT(size):
    matrix = np.zeros((size, size), dtype=complex)
    for k in range(size):
        for n in range(size):
            matrix[k, n] = np.exp(-2j*np.pi*k*n/size)

    return np.round(matrix, 10)

# Create DCT matricies
A = DFT(4)[2]
np.outer(A.conj(), A.conj())

array([[ 1.-0.j, -1.+0.j,  1.-0.j, -1.+0.j],
       [-1.+0.j,  1.-0.j, -1.+0.j,  1.-0.j],
       [ 1.-0.j, -1.+0.j,  1.-0.j, -1.+0.j],
       [-1.+0.j,  1.-0.j, -1.+0.j,  1.-0.j]])

In [165]:
DFT(4).conj()

array([[ 1.-0.j,  1.-0.j,  1.-0.j,  1.-0.j],
       [ 1.-0.j,  0.+1.j, -1.+0.j, -0.-1.j],
       [ 1.-0.j, -1.+0.j,  1.-0.j, -1.+0.j],
       [ 1.-0.j, -0.-1.j, -1.+0.j,  0.+1.j]])

In [166]:
np.array([[1, 0, 0, 0], [0, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]) @ DFT(4).conj()


array([[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 1.+0.j, -1.+0.j,  1.+0.j, -1.+0.j],
       [ 1.+0.j,  0.-1.j, -1.+0.j,  0.+1.j]])

In [167]:
np.array([[1, 1, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 1, 1]]) @ DCT(4).T

array([[ 2.        ,  1.84775907,  0.        , -0.76536686],
       [ 1.        ,  0.5411961 , -1.        , -1.30656296],
       [ 1.        , -0.5411961 , -1.        ,  1.30656296],
       [ 2.        , -1.84775907,  0.        ,  0.76536686]])

In [168]:
np.round(DCT(4) @ np.array([[1, 1, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 1, 1]]) @ DCT(4).T, 5)

array([[ 6.     ,  0.     , -2.     , -0.     ],
       [-0.     ,  5.41421,  0.     , -3.41421],
       [ 2.     ,  0.     ,  2.     ,  0.     ],
       [-0.     ,  0.58579,  0.     ,  2.58579]])

In [169]:
q = np.cos(np.pi/8)*np.sqrt(2)
r = np.cos(3*np.pi/8)*np.sqrt(2)
2*(q**2 + r**2 + q*r)

5.414213562373096

In [170]:
V = np.array([
    [186, -18, 15, -9, 23, -9, -14, 19],
    [21, -34, 26, -9, -11, 11, 14, 7],
    [-10, -24, -2, 6, -18, 3, -20, -1],
    [-8, -5, 14, -15, -8, -3, -3, 8],
    [-3, 10, 8, 1, -11, 18, 18, 15],
    [4, -2, -18, 8, 8, -4, 1, -7],
    [9, 1, -3, 4, -1, -7, -1, -2],
    [0, -8, -2, 2, 1, 4, -6, 0]
])

In [171]:
def Q(size, quality):
    matrix = np.zeros((size, size))
    for k in range(size):
        for l in range(size):
            matrix[k, l] = 1 + (1 + k + l)*quality
    return matrix

Q(8, 8)

array([[  9.,  17.,  25.,  33.,  41.,  49.,  57.,  65.],
       [ 17.,  25.,  33.,  41.,  49.,  57.,  65.,  73.],
       [ 25.,  33.,  41.,  49.,  57.,  65.,  73.,  81.],
       [ 33.,  41.,  49.,  57.,  65.,  73.,  81.,  89.],
       [ 41.,  49.,  57.,  65.,  73.,  81.,  89.,  97.],
       [ 49.,  57.,  65.,  73.,  81.,  89.,  97., 105.],
       [ 57.,  65.,  73.,  81.,  89.,  97., 105., 113.],
       [ 65.,  73.,  81.,  89.,  97., 105., 113., 121.]])

In [172]:
Y = np.round(V / Q(8, 8), 0)
Y

array([[21., -1.,  1., -0.,  1., -0., -0.,  0.],
       [ 1., -1.,  1., -0., -0.,  0.,  0.,  0.],
       [-0., -1., -0.,  0., -0.,  0., -0., -0.],
       [-0., -0.,  0., -0., -0., -0., -0.,  0.],
       [-0.,  0.,  0.,  0., -0.,  0.,  0.,  0.],
       [ 0., -0., -0.,  0.,  0., -0.,  0., -0.],
       [ 0.,  0., -0.,  0., -0., -0., -0., -0.],
       [ 0., -0., -0.,  0.,  0.,  0., -0.,  0.]])

In [173]:
# Zig Zag reorder
first = np.arange(0, 8*8).reshape(8, 8)
def zig_zag_value(i, j, n):
    # upper side of interval
    if i + j >= n:
        return n * n - 1 - zig_zag_value(n - 1 - i, n - 1 - j, n)
    # lower side of interval
    k = (i + j) * (i + j + 1) // 2
    return k + i if (i + j) & 1 else k + j


def zigzag(y):
    size = y.shape[0]
    z = np.zeros(size*size)
    for k in range(size):
        for n in range(size):
            z[zig_zag_value(k, n, 8)] = y[k, n]
    return z

z = zigzag(Y)
z

array([21., -1.,  1., -0., -1.,  1., -0.,  1., -1., -0., -0., -0., -0.,
       -0.,  1., -0., -0.,  0.,  0.,  0.,  0.,  0., -0.,  0., -0., -0.,
        0., -0.,  0.,  0.,  0., -0.,  0., -0.,  0.,  0., -0., -0.,  0.,
       -0., -0., -0.,  0., -0., -0.,  0.,  0.,  0., -0.,  0., -0., -0.,
        0.,  0.,  0.,  0., -0.,  0.,  0., -0., -0., -0., -0.,  0.])

In [176]:
# The vector generated in (c) is output according to the following rules:
# 1. each number between −128 and 127 is output as one byte;
# 2. each sequence of one or more zeros, a run, is output as two bytes (one equal to 0 and the other containing the number of zeros in the run)
# 3. each number smaller than −128 or larger than 127 is output as three bytes (one equal to −128, and two containing the actual number).

def calculate_storage(z):
    storage = 0
    i = 0
    while (i < len(z)):
        stp = storage
        # print(int(z[i]) == 0)
        if (z[i] >= 127 or z[i] <= -128):
            storage += 3
        elif (z[i] < 127 and z[i] > -128 and int(z[i]) != 0):
            storage += 1
        elif (int(z[i]) == 0):
            storage += 2
            while (i + 1 < len(z) and int(z[i + 1]) == 0):
                i += 1
        i += 1
        # print(storage - stp)
    return storage

calculate_storage(z)

16